{
 "title": "Technical",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidad Gateway",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway - Conteo Peticiones Voting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"gateway\", uri=\"/voting\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway - Conteo Peticiones Login",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"gateway\", uri=\"/login\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito Gateway",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=\"gateway\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=\"gateway\", uri=\"/voting\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencias Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"gateway\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval]))/sum(rate(http_server_requests_seconds_count{job=\"gateway\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"service-voting\", uri=\"/voting\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por Segundo Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"gateway\",uri=\"/voting\" }[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disponibilidad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "UP Voting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"service-voting\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP Java",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"service-java\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP Python",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"service-python\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP Ruby",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"service-ruby\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Conteo Peticiones Voting",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"service-voting\", uri=\"/voting\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conteo Peticiones Java",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conteo Peticiones Python",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_duration_seconds_count{job=\"service-python\", path=\"/logistic/route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conteo Peticiones Ruby",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=\"service-ruby\", path=\"/route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito Voting",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=\"service-voting\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=\"service-voting\", uri=\"/voting\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito Java",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\", outcome=\"SUCCESS\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito Python",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(flask_http_request_duration_seconds_count{job=\"service-python\", path=\"/logistic/route\", status=\"200\"}[$__rate_interval])) / sum(rate(flask_http_request_duration_seconds_count{job=\"service-python\", path=\"/logistic/route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje Exito Ruby",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_total{job=\"service-ruby\", path=\"/metrics\", code=\"200\"}[$__rate_interval])) / sum(rate(http_server_requests_total{job=\"service-ruby\", path=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por Segundo Voting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"service-voting\",uri=\"/voting\" }[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por segundo Java",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"service-java\",uri=\"/api/v1/routes/optimal-order\" }[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por Segundo Python",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{job=\"service-python\", path=\"/logistic/route\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operaciones por segundo Ruby",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{job=\"service-ruby\", path=\"/route\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Latencias Voting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"service-voting\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval]))/sum(rate(http_server_requests_seconds_count{job=\"service-voting\", uri=\"/voting\", outcome=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"service-voting\", uri=\"/voting\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencias Java",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\", outcome=\"SUCCESS\"}[$__rate_interval]))/sum(rate(http_server_requests_seconds_count{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\", outcome=\"SUCCESS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"service-java\", uri=\"/api/v1/routes/optimal-order\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencias Python",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{job=\"service-python\", path=\"/logistic/route\", status=\"200\"}[$__rate_interval]))/sum(rate(flask_http_request_duration_seconds_count{job=\"service-python\",path=\"/logistic/route\",status=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencias Ruby",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{job=\"service-ruby\", path=\"/route\"}[$__rate_interval]))/sum(rate(http_server_request_duration_seconds_count{job=\"service-ruby\",path=\"/route\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU & Memoria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Voting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"service-voting\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Java",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"service-java\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria Voting",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"service-voting\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"service-voting\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"service-voting\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria Java",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"service-java\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"service-voting\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"service-voting\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}